ptf @
cropnum,parname,parvalue
 SFAC,KC_SFAC,@KC_SFAC           @
 1,KC_CITRUS_AND_SUBTROPICAL,@KC_CITRUS_AND_SUBTROPICAL       @
 2,KC_DECIDUOUS_FRUITS_AND_NUTS,@KC_DECIDUOUS_FRUITS_AND_NUTS    @
 3,KC_FIELD_CROP, @KC_FIELD_CROP                   @
 4,KC_GRAIN_AND_HAY_CROPS,@KC_GRAIN_AND_HAY_CROPS          @
 5,KC_IDLE,@KC_IDLE                         @
 6,KC_NATIVE_VEGETATION_RIPARIAN,@KC_NATIVE_VEGETATION_RIPARIAN   @
 7,KC_PASTURE,@KC_PASTURE                      @
 8,KC_SEMIAGRICULTURAL,@KC_SEMIAGRICULTURAL             @
 9,KC_SEMIPAVED,@KC_SEMIPAVED                    @
10,KC_TRUCK_NURSERY_AND_BERRY_CROPS   @KC_TRUCK_NURSERY_AND_BERRY_CROPS@
11,KC_TURF,@KC_TURF                         @
12,KC_VINEYARD,@KC_VINEYARD                     @
13,KC_WALNUTS,@KC_WALNUTS                      @
14,KC_WATER,@KC_WATER                        @