ptf @
cropnum,parname,parvalue
 1,OFE_CITRUS_AND_SUBTROPICAL,@OFE_CITRUS_AND_SUBTROPICAL       @
 2,OFE_DECIDUOUS_FRUITS_AND_NUTS,@OFE_DECIDUOUS_FRUITS_AND_NUTS    @
 3,OFE_FIELD_CROP, @OFE_FIELD_CROP                   @
 4,OFE_GRAIN_AND_HAY_CROPS,@OFE_GRAIN_AND_HAY_CROPS          @
 5,OFE_IDLE,@OFE_IDLE                         @
 6,OFE_NATIVE_VEGETATION_RIPARIAN,@OFE_NATIVE_VEGETATION_RIPARIAN   @
 7,OFE_PASTURE,@OFE_PASTURE                      @
 8,OFE_SEMIAGRICULTURAL,@OFE_SEMIAGRICULTURAL             @
 9,OFE_SEMIPAVED,@OFE_SEMIPAVED                    @
10,OFE_TRUCK_NURSERY_AND_BERRY_CROPS,   @OFE_TRUCK_NURSERY_AND_BERRY_CROPS@
11,OFE_TURF,@OFE_TURF                         @
12,OFE_VINEYARD,@OFE_VINEYARD                     @
13,OFE_WALNUTS,@OFE_WALNUTS                      @
14,OFE_WATER,@OFE_WATER                        @